# Cosmos Discord Faucet configuration

verbose        = "yes"

[cosmos]
prefix         = "cosmos"
denomination   = "uatom"

[testnets]
    [testnets.theta]
    node_url = "http://state-sync-01.theta-testnet.polypore.xyz:26657"
    chain_id = "theta-testnet-001"
    faucet_address = "cosmos15aptdqmm7ddgtcrjvc5hs988rlrkze40l4q0he"
    block_explorer_tx = "https://explorer.theta-testnet.polypore.xyz/transactions"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "500"

    [testnets.devnet]
    node_url = "http://one.theta-devnet.polypore.xyz:26657"
    chain_id = "theta-devnet"
    faucet_address = "cosmos15aptdqmm7ddgtcrjvc5hs988rlrkze40l4q0he"
    block_explorer_tx = ""
    daily_cap = "50000000"
    amount_to_send = "1000000"
    tx_fees = "500"

[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = "test-channel"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "86400"