# Cosmos Discord Faucet configuration

verbose        = "yes"
transactions_log = "transactions.csv"

[chains]
    [chains.chain-1]
    binary = "gaiad"
    home_folder = "~/.gaia"
    prefix = "cosmos"
    denom = "uatom"
    node_url = "http://localhost:26657"
    chain_id = "test-gaiad-1"
    faucet_address = "cosmos..."
    block_explorer_tx = "https://chain1.explorer.com/tx/"
    daily_cap = "250000000"
    amount_to_send = "1000"
    tx_fees = "1000"
    description = "My Gaia testnet"
    website = ""

    [chains.chain-2]
    binary = "simd"
    home_folder = "~/.simd"
    prefix = "cosmos"
    denom = "stake"
    node_url = "http://localhost:26658"
    chain_id = "test-simd-1"
    faucet_address = "cosmos..."
    block_explorer_tx = "https://chain2.explorer.com/tx/"
    daily_cap = "250000000"
    amount_to_send = "1000"
    tx_fees = "1000"
    description = "My simd testnet"
    website = ""

[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = ""
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout  = "86400"